version: '3.8'

services:
  streamlit:
    build: .
    container_name: streamlit_app
    ports:
      - "8501:8501"
    restart: always
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro 
      - ./logs:/var/log/nginx                  
    ports:
      - "80:80"
    depends_on:
      - streamlit
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
